final List<Map<String, dynamic>> sampleJson = [
  {
    "channel_id": 1,
    "channel_name": "Admin",
    "channel_thumbnail":
        "https://ik.imagekit.io/imageurl/7309670_24UoqelD8.jpg",
    "id": 5,
    "description": "",
    "post_type": "normal",
    "button_text": "Open",
    "button_color": "FF6961",
    "link_open": "none",
    "link": "",
    "share_text": "This is a sample sharing text",
    "share_link": "www.testsharinglink.com",
    "share_image": "",
    "image_size": "",
    "post_image": ["https://ik.imagekit.io/imageurl/1x_Qrkyf0gCMt.png"],
    "youtube": {"thumbnail": "", "youtube_link": ""},
    "video": {"thumbnail": "", "video_link": "", "video_size": ""},
    "hashtags": "#CC",
    "post_category": "Stories,Events,Placements,Scholarships",
    "whatsapp_join_status": false,
    "channel_subscribed": false,
    "created_at": "2025-04-07T17:02:44.587Z",
    "listing_order": 2,
    "publish": true,
    "total_shares": 50,
    "total_likes": 50,
    "total_saves": 50,
    "university": {"id": 1, "name": "Other"},
    "course": {"id": 1, "name": "Other"},
    "stream": {"id": 1, "name": "Other"},
    "semester": {"id": 1, "name": "Other"},
    "audio": {"duration": "", "thumbnail": "", "audio_link": ""}
  },
  {
    "channel_id": 2,
    "channel_name": "Admin",
    "channel_thumbnail":
        "https://ik.imagekit.io/imageurl/7309670_24UoqelD8.jpg",
    "id": 5,
    "description": "",
    "post_type": "normal",
    "button_text": "Open",
    "button_color": "FF6961",
    "link_open": "none",
    "link": "",
    "share_text": "This is a sample sharing text",
    "share_link": "www.testsharinglink.com",
    "share_image": "",
    "image_size": "",
    "post_image": ["https://ik.imagekit.io/imageurl/1x_Qrkyf0gCMt.png"],
    "youtube": {"thumbnail": "", "youtube_link": ""},
    "video": {"thumbnail": "", "video_link": "", "video_size": ""},
    "hashtags": "#CC",
    "post_category": "Stories,Events,Placements,Scholarships",
    "whatsapp_join_status": false,
    "channel_subscribed": false,
    "created_at": "2025-04-07T17:02:44.587Z",
    "listing_order": 2,
    "publish": true,
    "total_shares": 50,
    "total_likes": 50,
    "total_saves": 50,
    "university": {"id": 1, "name": "Other"},
    "course": {"id": 1, "name": "Other"},
    "stream": {"id": 1, "name": "Other"},
    "semester": {"id": 1, "name": "Other"},
    "audio": {"duration": "", "thumbnail": "", "audio_link": ""}
  },
  {
    "channel_id": 3,
    "channel_name": "Admin",
    "channel_thumbnail":
        "https://ik.imagekit.io/imageurl/7309670_24UoqelD8.jpg",
    "id": 5,
    "description": "",
    "post_type": "normal",
    "button_text": "Open",
    "button_color": "FF6961",
    "link_open": "none",
    "link": "",
    "share_text": "This is a sample sharing text",
    "share_link": "www.testsharinglink.com",
    "share_image": "",
    "image_size": "",
    "post_image": ["https://ik.imagekit.io/imageurl/1x_Qrkyf0gCMt.png"],
    "youtube": {"thumbnail": "", "youtube_link": ""},
    "video": {"thumbnail": "", "video_link": "", "video_size": ""},
    "hashtags": "#CC",
    "post_category": "Stories,Events,Placements,Scholarships",
    "whatsapp_join_status": false,
    "channel_subscribed": false,
    "created_at": "2025-04-07T17:02:44.587Z",
    "listing_order": 2,
    "publish": true,
    "total_shares": 50,
    "total_likes": 50,
    "total_saves": 50,
    "university": {"id": 1, "name": "Other"},
    "course": {"id": 1, "name": "Other"},
    "stream": {"id": 1, "name": "Other"},
    "semester": {"id": 1, "name": "Other"},
    "audio": {"duration": "", "thumbnail": "", "audio_link": ""}
  }
];
